# Generated by Django 2.1.7 on 2019-03-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=30)),
                ('encrypted', models.CharField(max_length=200)),
                ('decrypted', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemno', models.IntegerField(db_column='Itemno')),
                ('category', models.CharField(db_column='Category', max_length=20)),
                ('foodname', models.CharField(db_column='FoodName', max_length=30)),
                ('company', models.CharField(db_column='Company', max_length=20)),
                ('price', models.IntegerField(db_column='Price')),
            ],
        ),
    ]
