# Generated by Django 2.1.7 on 2019-03-05 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190305_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title', '-id']},
        ),
    ]
